name: PlatformIO Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PlatformIO
        uses: platformio/platformio-action@v3
        with:
          platform: 'arduino'

      - name: Build firmware
        run: platformio run
